/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ShareShareIdRouteImport } from './routes/share.$shareId'
import { Route as DashboardTrashRouteImport } from './routes/dashboard/trash'
import { Route as DashboardSharedRouteImport } from './routes/dashboard/shared'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as DashboardFolderFolderIdRouteImport } from './routes/dashboard/folder/$folderId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTrashRoute = DashboardTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSharedRoute = DashboardSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFolderFolderIdRoute = DashboardFolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/shared': typeof DashboardSharedRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/folder/$folderId': typeof DashboardFolderFolderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/shared': typeof DashboardSharedRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/folder/$folderId': typeof DashboardFolderFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/shared': typeof DashboardSharedRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/folder/$folderId': typeof DashboardFolderFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/account'
    | '/dashboard/shared'
    | '/dashboard/trash'
    | '/share/$shareId'
    | '/dashboard/'
    | '/dashboard/folder/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/account'
    | '/dashboard/shared'
    | '/dashboard/trash'
    | '/share/$shareId'
    | '/dashboard'
    | '/dashboard/folder/$folderId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/account'
    | '/dashboard/shared'
    | '/dashboard/trash'
    | '/share/$shareId'
    | '/dashboard/'
    | '/dashboard/folder/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/trash': {
      id: '/dashboard/trash'
      path: '/trash'
      fullPath: '/dashboard/trash'
      preLoaderRoute: typeof DashboardTrashRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/shared': {
      id: '/dashboard/shared'
      path: '/shared'
      fullPath: '/dashboard/shared'
      preLoaderRoute: typeof DashboardSharedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/folder/$folderId': {
      id: '/dashboard/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/dashboard/folder/$folderId'
      preLoaderRoute: typeof DashboardFolderFolderIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardSharedRoute: typeof DashboardSharedRoute
  DashboardTrashRoute: typeof DashboardTrashRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardFolderFolderIdRoute: typeof DashboardFolderFolderIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardSharedRoute: DashboardSharedRoute,
  DashboardTrashRoute: DashboardTrashRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardFolderFolderIdRoute: DashboardFolderFolderIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ShareShareIdRoute: ShareShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
